openapi: 3.1.0
info:
  version: 1.0.0
  title: My cocntacts app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of my cocntacts app
tags:
  - name: Contacts
    description: Operations about cocntacts.
  - name: Auth
    description: Auth operations.
servers:
  - url: http://localhost:3000
  # - url: #посилання на задеплоєний сайт
paths:
  /contacts/{id}:
    get:
      $ref: ../swagger/path/contacts/{id}/get.yaml
    put:
      $ref: ../swagger/path/contacts/{id}/put.yaml
    patch:
      $ref: ../swagger/path/contacts/{id}/patch.yaml
    delete:
      $ref: ../swagger/path/contacts/{id}/delete.yaml
  /contacts:
    get:
      $ref: ../swagger/path/contacts/get.yaml
    post:
      $ref: ../swagger/path/contacts/post.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
